### ISSUE TITLE
Error: The incoming JSON object does not contain a client_email field

### ISSUE THREAD

**Issue by rppig** [google/google-auth-library-nodejs#137] opened 2017-05-01 17:24 UTC
I get this error when I'm using a OAuth client ID JSON file as GOOGLE_APPLICATION_CREDENTIALS.

Here's the content of this JSON file.
```
{
    "installed": {
        "client_id": "",
        "project_id": "",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://accounts.google.com/o/oauth2/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
        "client_secret": "",
        "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
    }
}
```

Here's the code where I get this error.
```
var GoogleAuth = require("google-auth-library");
new GoogleAuth().getApplicationDefault(function(err, auth) {
  console.log(err);
});
```

**Comment by lukesneeringer** [comment] 2017-09-06 18:59
I am pretty sure we require `client_email`. Did you download this JSON file from one of our systems?

**Comment by daywaves** [comment] 2017-09-30 07:06
I'm having the same problem and I have a JSON file with the exact same format (no `client_email` field). I got my JSON file from the Google API developer console to work with the Gmail API. My file is also an OAuth 2.0 Client ID. I tried making a service account credential instead and that file did have a `client_email` field, but I think I need to use OAuth2 not a service account.

**Comment by bantini** [comment] 2017-10-02 18:41
@daywaves You should use the service account JSON for OAuth2 authentication. Can you describe what you are trying to do, and where it is failing?

**Comment by JustinBeckwith** [comment] 2017-12-30 22:53
You are mixing things up a bit :)  You need to create a "Service account key" if you want to use this for service->service communication, where your account is used to perform actions.  

![image](https://user-images.githubusercontent.com/534619/34457784-d77c9286-ed89-11e7-91c8-ce7961ae79c6.png)

If you want to use the credentials of the user to perform actions on behalf of the user, you want to use OAuth2.  In that case - you wouldn't use application default credentials, rather a [standard OAuth2 workflow](https://github.com/google/google-auth-library-nodejs/blob/next/examples/oauth2.js). 

We have some improved docs to cover this stuff sitting over in the [next branch](https://github.com/google/google-auth-library-nodejs/tree/next).   I'm going to close this out for now - feel free to keep asking questions!

**Closed by JustinBeckwith** 2017-12-30 22:53 UTC
Labels: needs information, Type: Question

**Comment by bbhoss** [comment] 2018-03-20 19:21
This doesn't seem accurate. The Ruby gem for authenticating (particularly with Google Cloud Storage) does not require a client_email in order to operate.

**Comment by bbhoss** [comment] 2018-03-20 19:53
So, I haven't dug really deep into the Ruby library, but the functionality seems to be located here: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/master/google-cloud-core/lib/google/cloud/credentials.rb#L49

I confirmed locally that loading a bucket and listing its files doesn't require a client_email, while the node client generates an error. It seems the Ruby client allows it to not be present, but also allows it to be passed in discretely.

**Comment by n0bisuke** [comment] 2021-07-05 04:10
A similar problem arose. Thank you.

**Comment by tsaxking** [comment] 2023-04-30 21:15
Hello, I hate to message on old threads, but I just encountered this issue as well. Is there a solution somewhere I am not seeing?

**Comment by LeandroBaroni** [comment] 2024-07-31 04:45
I`m followin the google calendar API docs in a NodeTS project and getting the same issue. This is my credentials.json.
Is there something that i dont`t notice in the docs or this JSON?
`{
  "web":{
    "client_id":"client_id.com",
    "project_id":"project-homol",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"client_secret"
  }
}
`

**Comment by ashuprajapat** [comment] 2024-10-29 10:01
I am facing the same issue, do we have solution to this one ? 
I am using Workload identity federation and package is googleauth-1.6.0. The json file is {
      "type": "external_account",
      "audience": "",
      "subject_token_type": "",
      "token_url": "",
      "credential_source": {
      "file": "",
        "format": {
        "type": "text"
      }
    },
    "service_account_impersonation_url": ""
    }

**Comment by m-shum** [comment] 2025-01-07 16:41
Having the same issue when passing the result of `new GoogleAuthLibrary.GoogleAuth()` to `GoogleAnalytics.reports.batchGet` as the `auth` param. The object returned by `GoogleAuthLibrary.GoogleAuth()` does not include a `client_email` property – only the credentials passed TO gauth when generating an auth object contain that field.

**Comment by adrianbartyczak** [comment] 2025-02-22 01:00
Google = dogs***

**Comment by joshamaju** [comment] 2025-04-30 09:03
I'm stuck on this too, any help?
