### ISSUE TITLE
JWT access token is created every time you call getRequestMetadata

### ISSUE THREAD

**Issue by jtattermusch** [google/google-auth-library-nodejs#49] opened 2015-08-06 22:56 UTC
It looks like the JWT access token auth implementation  creates a new JWT access token every time you call getRequestMetadata, instead of reusing a token created previously (if that one is still valid and has the same authUri).

see https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/jwtaccess.js#L55

This brings two problems:
-- the auth headers will be different every time you make an RPC (issue time will differ so the access token will also be different), and HTTP/2 header compression won't be able to cache the header that is considerably larger in size than a regular OAuth2 token.
-- additional overhead signing the JWT for each request (not sure how much of an issue, but I think I can be a problem under heavy load).

The exact way of caching JWT access tokens needs some thought - it needs to correctly handle token expiration and handle access tokens for different authUris separately.

it would also be good to investigate how do JWT access token implementations in other languages (Ruby, Java, etc.) handle this, I wouldn't be too surprised if they were behaving the same as node.

**Comment by jtattermusch** [comment] 2015-08-06 22:57
@anthmgoogle, can you please take a look at this? I don't have rights to assign issues on this repo.

@tbetbetbe FYI

**Comment by tbetbetbe** [comment] 2015-08-07 17:41
> The exact way of caching JWT access tokens needs some thought - it needs to correctly handle token > expiration and handle access tokens for different authUris separately.

Note that Node.js and the other google-auth libraries already have logic for caching tokens based on expiration time, otherwise they would continuously request auth tokens in the standard non-JWT scenarios - they don't do this.

The necessary changes are
- [ ] upgrade the existing expiration logic to be able to support multiple tokens with a combination key expiration time and an arbitrary sting
- [ ] update the jwt implementation so that it begins to use the expiration logic

**Comment by anthmgoogle** [comment] 2015-08-10 19:26
Yes, we should implement a consistent form of caching in all the client libraries. We should probably use the audience as key for caching, but also have a form of time expatriation. I'm tracking some consistency items across the libraries. I'll make sure we have a line item for this and bugs in each client library.

**Comment by tbetbetbe** [comment] 2015-08-11 02:56
This is a duplicate of #52, lets use that

**Closed by tbetbetbe** 2015-08-11 02:56 UTC
