### ISSUE TITLE
Google-auth-library-nodejs depends on base64url, and they have a typescript bug

### ISSUE THREAD

**Issue by dauledk** [google/google-auth-library-nodejs#179] opened 2017-11-08 18:46 UTC
This project is using base64url as a dependency. 

[Base64url have a bug](https://github.com/brianloveswords/base64url/issues/20), since they include **global typings**. This gives a lot of errors when using typescript. 

To fix this problem, I added the following gulp task to remove the problematic files: 

```javascript
gulp.task('clean-script', function(){
    return del([
        'node_modules/base64url/typings',
        'node_modules/base64url/dist/base64url.d.ts',
    ]);
});
```

Maybe this project could use [the other base64url project](https://github.com/joaquimserafim/base64-url)?

**Comment by ofrobots** [comment] 2017-11-09 02:19
Thank you for tracking this down! We'll looking into switching our dependencies.

**Comment by JustinBeckwith** [comment] 2017-11-25 18:29
Thanks for reporting!  I'm trying this out, and struggling to reproduce any issues.  What exact kind of errors are you getting?  Any repro steps?  Just want to make sure we actually fix the issue :)

**Comment by dauledk** [comment] 2017-11-26 09:17
Hi @JustinBeckwith - it is related to typings when you use typescript. Maybe thats why you can't reproduce?

**Comment by JustinBeckwith** [comment] 2017-11-26 17:57
So here's what I'm seeing.  I have a package.json with these deps:
```
"dependencies": {
    "google-auth-library": "^0.12.0"
  },
  "devDependencies": {
    "@types/node": "^8.0.53",
    "@types/request": "^2.0.8",
    "gts": "^0.5.1",
    "typescript": "^2.6.1"
  }
```

After I do that, I can write this code:

```js
const GoogleAuth = require('google-auth-library');
console.log(GoogleAuth);
const auth = new GoogleAuth();
const jwt = new auth.JWT();
console.log(auth);
console.log(jwt);
```

And it compiles.  That having been said - needing to use the `require` instead of es module import kills any real advantage to having a typescript type.  Be careful to `npm install --save-dev @types/request` because of a bug in the current version.  What specifically are you seeing when you try to compile?

It would be super helpful if you could try this out for us on our development branch.  This will let us know if the issue is fixed in the next version.  To try that, install from GitHub:

`npm install google/google-auth-library-nodejs#next`

Then give code like this a try:

```js
import {GoogleAuth} from 'google-auth-library';
console.log(GoogleAuth);
const auth = new GoogleAuth();
const jwt = new auth.JWT();
async function getToken() {
  const token = await jwt.getToken('token');
  console.log(token);
  return token;
}
getToken();
```

**Comment by dauledk** [comment] 2017-11-26 20:21
Ok - so here is what I did on a mac os with nodejs v8.9.1, npm 5.5.1 and tsc 2.6.1: 

1. mkdir google-auth && cd google-auth
2. insert the following package.json
```javascript
"dependencies": {
    "google-auth-library": "github:google/google-auth-library-nodejs#next"
  },
  "devDependencies": {
    "@types/node": "^8.0.53",
    "@types/request": "^2.0.8",
    "gts": "^0.5.1",
    "typescript": "^2.6.1"
  }
```
3. insert the following tsconfig.json file
```
{
  "compilerOptions": {
    "target": "es6",                         
    "module": "commonjs",                    
    "strict": true                           
  },
  "exclude": [
    "node_modules"
  ]
}
```
4. instert the following main.ts file
```typescript
import { GoogleAuth } from 'google-auth-library';

console.log(GoogleAuth);
const auth = new GoogleAuth();
const jwt = new auth.JWT();
async function getToken() {
  const token = await jwt.getToken('token');
  console.log(token);
  return token;
}
getToken();
```
5. npm i && tsc && node main.js. This gives the following error:
```
main.ts(1,28): error TS2307: Cannot find module 'google-auth-library'.
```
<img width="593" alt="screen shot 2017-11-26 at 21 19 47" src="https://user-images.githubusercontent.com/9967422/33243972-a50110de-d2ef-11e7-9543-c0b78daac383.png">

**Comment by JustinBeckwith** [comment] 2017-11-26 20:50
Eugh, installing the npm module directly from GitHub doesn't work because it's TypeScript.  
[google-auth-library-0.11.0.zip](https://github.com/google/google-auth-library-nodejs/files/1504221/google-auth-library-0.11.0.zip)

Thank you so much for bearing with me.  Please try to download that zip, rename it to google-auth-library-0.11.0.tgz, and `npm install` that.

**Comment by dauledk** [comment] 2017-11-27 08:44
ok so I downloaded the google-auth-library, renamed and installed with npm i google-auth-library-0.11.0.tgz. 

Same error, `Error: Cannot find module 'google-auth-library'`

**Comment by JustinBeckwith** [comment] 2017-11-29 02:54
This is fixed in the `next` branch, and will be part of the upcoming 1.0 release.

**Closed by JustinBeckwith** 2017-11-29 02:54 UTC
